"""
OB1 Serie C - PDF Reporter
Genera report settimanali stampabili per Direttori Sportivi
"""

import os
from datetime import datetime
from fpdf import FPDF
from typing import List, Dict

class OB1Report(FPDF):
    def header(self):
        # Title
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 10, 'OB1 SCOUTING REPORT', align='L', new_x="LMARGIN", new_y="NEXT")
        
        # Subtitle
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Serie C & D Market Intelligence - {datetime.now().strftime("%d/%m/%Y")}', align='L', new_x="LMARGIN", new_y="NEXT")
        
        self.ln(5)
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by OB1 AI Scout', align='C')

class ReportGenerator:
    def __init__(self, output_dir: str = "docs/reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_weekly_report(self, opportunities: List[Dict], dna_matches: List[Dict] = None):
        pdf = OB1Report()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # 1. MARKET OVERVIEW
        self._add_section_title(pdf, "MARKET OVERVIEW")
        
        total = len(opportunities)
        hot = len([o for o in opportunities if o.get('ob1_score', 0) >= 80])
        warm = len([o for o in opportunities if 60 <= o.get('ob1_score', 0) < 80])
        
        pdf.set_font('Helvetica', '', 12)
        pdf.set_text_color(0)
        pdf.cell(0, 10, f"Totale Opportunita Monitorate: {total}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 10, f"HOT Leads (Score 80+): {hot}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 10, f"Warm Leads (Score 60-79): {warm}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # 2. TOP OPPORTUNITIES (HOT LIST)
        self._add_section_title(pdf, "TOP OPPORTUNITIES (HOT LIST)")
        
        # Table Header
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        
        # Columns: Name (40), Age (15), Role (20), Club/Status (50), Score (15), Value (30)
        pdf.cell(50, 10, "Giocatore", border=1, fill=True)
        pdf.cell(15, 10, "Eta", border=1, fill=True, align='C')
        pdf.cell(20, 10, "Ruolo", border=1, fill=True, align='C')
        pdf.cell(60, 10, "Club / Status", border=1, fill=True)
        pdf.cell(15, 10, "Score", border=1, fill=True, align='C')
        pdf.ln()
        
        # Table Body
        pdf.set_font('Helvetica', '', 9)
        hot_list = sorted([o for o in opportunities if o.get('ob1_score', 0) >= 75], 
                         key=lambda x: x.get('ob1_score', 0), reverse=True)[:15]
        
        for opp in hot_list:
            name = self._clean_text(opp.get('player_name', 'N/A'))
            age = str(opp.get('age', '-'))
            role = opp.get('role', '-')
            club = self._clean_text(opp.get('current_club', 'Svincolato') or 'Svincolato')
            score = str(opp.get('ob1_score', 0))
            
            # Truncate long texts
            if len(club) > 30: club = club[:27] + "..."
            if len(name) > 25: name = name[:22] + "..."
            
            pdf.cell(50, 10, name, border=1)
            pdf.cell(15, 10, age, border=1, align='C')
            pdf.cell(20, 10, role, border=1, align='C')
            pdf.cell(60, 10, club, border=1)
            
            # Highlight high scores
            pdf.set_font('Helvetica', 'B', 9)
            pdf.cell(15, 10, score, border=1, align='C')
            pdf.set_font('Helvetica', '', 9)
            
            pdf.ln()

        pdf.ln(10)

        # 3. DNA MATCHES (If available)
        if dna_matches:
            self._add_section_title(pdf, "DNA MATCHES: TALENTI SQUADRE B")
            pdf.set_font('Helvetica', '', 10)
            pdf.multi_cell(0, 6, "Giovani talenti dalle squadre B (Juve NG, Milan Futuro, Atalanta U23) raccomandati per la Serie C.")
            pdf.ln(5)
            
            for match in dna_matches[:5]:
                player = match.get('player', {})
                score = match.get('score', 0)
                club_dna = match.get('club', {}).get('name', 'General')
                
                txt = f"{score}% MATCH - {player.get('name')} ({player.get('primary_position')}, {2026 - player.get('birth_year', 2000)}) - {player.get('current_team')}"
                pdf.set_font('Helvetica', 'B', 10)
                pdf.cell(0, 8, txt, new_x="LMARGIN", new_y="NEXT")
                
                # Breakdown
                breakdown = match.get('breakdown', {})
                break_txt = f"   Fit Tattico: {breakdown.get('style')}% | Disponibilita: {breakdown.get('availability')}%"
                pdf.set_font('Helvetica', '', 9)
                pdf.cell(0, 6, break_txt, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)

        # Save
        filename = f"OB1_Report_{datetime.now().strftime('%Y%m%d')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        print(f"📄 PDF Report generato: {filepath}")
        return filepath

    def _add_section_title(self, pdf, title):
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_fill_color(50, 50, 100)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0)
        pdf.ln(5)

    def _clean_text(self, text):
        """Rimuove caratteri non supportati da Latin-1"""
        if not text: return ""
        # Sostituzioni basiche per caratteri comuni
        replacements = {
            'è': 'e', 'é': 'e', 'à': 'a', 'ì': 'i', 'ò': 'o', 'ù': 'u',
            '’': "'", '“': '"', '”': '"', '–': '-', '€': 'EUR '
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        
        # Encode/Decode per rimuovere altro
        return text.encode('latin-1', 'replace').decode('latin-1')

if __name__ == "__main__":
    # Test
    gen = ReportGenerator()
    dummy_opps = [
        {"player_name": "Mario Rossi", "age": 22, "role": "CC", "current_club": "Svincolato", "ob1_score": 85},
        {"player_name": "Luigi Verdi", "age": 28, "role": "AT", "current_club": "Pescara", "ob1_score": 75}
    ]
    gen.generate_weekly_report(dummy_opps)
